# -*- coding: utf-8 -*-
"""Practice_Problem_17ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cw1oOkSj2NeyCimlxcHtED2goR8NXYvp
"""

'''
@filename: PracProb_17.py
@authors: Adil Shafqat, Qianxun Tu, Daniel Rios
@description: The program rolls two dice, gets the sum of the two
rolls, then repeats this 1000 times and counts the number of occurences of the
possible sum outcomes (2 through 12). It then plots a histogram displaying the
number of instances each sum occurs.
@date: 11/8/23
@version: 1.00
'''

import random
import matplotlib.pyplot as plt

# initialize dictionary to store counts of each sum
results = {2:0, 3:0, 4:0, 5:0, 6:0, 7:0, 8:0, 9:0, 10:0, 11:0, 12:0}

# simulate rolling dice 1000 times
for i in range(1000):
  die1 = random.randint(1, 6)  # roll the first die
  die2 = random.randint(1, 6)  # roll the second die
  total = die1 + die2
  results[total] += 1   # update count of the current total in the results dictionary

print(results)

# extract keys and values of dictionary to lists for histogram
sums = list(results.keys())
counts = list(results.values())

# create histogram
plt.bar(sums, counts, tick_label=sums, align='center', color='skyblue')
plt.xlabel('Sum of Two Dice')
plt.ylabel('Frequency')
plt.title('Histogram of Sum of Two Dice (1000 Rolls)')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

# save the histogram as image file
plt.savefig('DicePlot.png')