# -*- coding: utf-8 -*-
"""Practice_problem_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1arINdRLYNMnd37w6ecTwJqE9brGvqQRC
"""

# create a function: loan(savings, age, house)
def loan(savings=0, age=0, house=False):
  '''
  @file name: Practice_problem_7
  @team: Group 8
  @authours: Adil Shafqat, Daniel Rios, Qianxun Tu
  @description: The user inputs what their savings are, what their age is,
  and if they have a house or not, and then the program outputs if the
  user will get a loan (true) or not (false), and also the amount of the loan
  @date created: 10/6/2023
  @version: 1.00
  '''
  amount = 0
  if age <= 30:
    #If you are 30 or less, you do not get a loan according to the table
    return False, 0
  elif savings > 100000:
    #If you are older than 30 and have more than 100K, you get a 150K loan
    return True, 150000
  if (30 < age <= 50):
    if house == False:
      return False, 0
      # if you are between the age of 30 and 50 in age and dont have a house you do not qualify for a loan
    else:
      if savings < 10000:
        return True, 30000
        # If you are between 30 and 50 in age, have a house, and less than 10000 in savings you qualify for a 30k loan
      elif 10000 <= savings < 20000:
        return True, 40000
           # If you are between 30 and 50 in age, have a house, and between 10000 and 20000 in savings you qualify for a 40k loan
      elif 20000 <= savings < 30000:
        return True, 50000
        # if you are between 30 and 50 in age, have a house, and between 20000 and 30000 in savings you qualify for a 50k loan
      else:
        return True, 100000
        # if you are between 30 and 50 in age, have a house, and more than 30000 in savings you qualify for a 100k loan
  if age > 50:
    if house == False:
      if 30000 <= savings < 100000:
        return True, 50000
        # if you are over 50 in age, do not have a house, and have between 30000 and 100000 in savings you qualify for a 50000 loan
    else:
      if savings < 10000:
        return True, 60000
        # if you are over 50 in age, have a house, and less than 10000 in savings you qualify for a 60k loan
      if 10000 <= savings < 20000:
        return True, 80000
        # if you are over 50 in age, have a house, and between 10000 and 20000 in savings you qualify for a 80k loan
      if 20000 <= savings < 30000:
        return True, 90000
        # if you are over 50 in age, have a house, and between 20000 and 30000 in savings you qualify for a 90k loan

print(loan(5000, 50, True))
print(loan(20000, 30, True))
print(loan(200000, 40, False))