# -*- coding: utf-8 -*-
"""PracProb_12

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iTqEUzWf-gApkL57RvnVZQV12DVaHIjD
"""

'''
@filename: PracProb_12.py
@team: Team 8
@authors: Adil Shafqat, Qianxun Tu, Daniel Rios
@description: The program stores students names, exam grades, and homework grades
in a dictionary and then calculates the students overall grade and stores that
in a nested dictionary. Once the user enters stop or a blank, the program then
displays each students name along with their grades.
@date: 10/23/23
@version: 1.00
'''
#Initialize grades as empty dictionary
grades = {}

#a while loop to input student information, ending when you input 'stop' or a
#blank space
while True:
    try:
        name = input("Enter student's name or 'stop' to quit: ")
        if name.lower() == 'stop' or name == '':
            break
#a nested empty dictionary that stores exam and homework grades for each student
        grades[name] = {}

#function asks user to input exam grades out of 100
        exams = input("Enter exam grades (out of 100) separated by commas: ")
        exam_list = [int(x) for x in exams.split(',')]

#input exam grades are stored in student's dictionary
        grades[name]['Exams'] = exam_list

#function asks user to input homework grades out of 50
        homework = input("Enter homework grades (out of 50) separated by commas: ")
        hw_list = [int(x) for x in homework.split(',')]

#input homework grades are stored in student's dictionary
        grades[name]['Homework'] = hw_list

#exception for case where user inputs non-integer value for grades
    except ValueError:
        print('Invalid input. Please enter valid grades separated by commas.')

#calculate average of exams, homework, and weighted overall grade for each student
#using a for loop
for name, data in grades.items():
    exam_avg = sum(data['Exams']) / len(data['Exams'])
    homework_avg_100 = (sum(data['Homework']) / len(data['Homework'])) * 2
    total_grade = 0.6 * exam_avg + 0.4 * homework_avg_100

#output students, name, exam average, homework average, and weighted overall grade
    print('')
    print(f"Student: {name}")
    print(f"Exam average: {exam_avg:.2f}%")
    print(f"Homework average: {homework_avg_100:.2f}%")
    print(f"Overall grade: {total_grade:.2f}%")