# -*- coding: utf-8 -*-
"""Practice_problem_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16Zstk9cWCOPTMEBtiYGQP7Pc4xS14M4G
"""



# Problem 4
def report_card():
  '''
@file name: Practice_Problem_4.py
@Group Team 8
@desciption: Designing report card
@authors: Adil Shafqat, Tiffany Tu, Daniel Rios
@date created: 09/29/2023
'''
  Class_1 = input('What was the name of your first class? ')
  Class_1_grade = int(input('What was your grade? '))
  Class_2 = input('What was the name of your second class? ')
  Class_2_grade = int(input('What was your grade? '))
  Class_3 = input('What was the name of your third class? ')
  Class_3_grade = int(input('What was your grade? '))
  Class_4 = input('What was the name of your fourth class? ')
  Class_4_grade = int(input('What was your grade? '))
  print("Report Card")
  print('===========')
  print(Class_1, Class_1_grade)
  print(Class_2, Class_2_grade)
  print(Class_3, Class_3_grade)
  print(Class_4, Class_4_grade)
  print('===========')
  GPA_100 = (Class_1_grade + Class_2_grade + Class_3_grade + Class_4_grade)/4
  GPA_4 = GPA_100 / 25
  print(GPA_100)
  print(GPA_4)
report_card()
