# -*- coding: utf-8 -*-
"""Practice_problem_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHV9TJmNXOU1BR4o1qrHYmgQAUtaRbrA
"""

def sum_average():
  '''
  @file name: Practice_problem_6
  @team: Team 8
  @authors: Adil Shafqat, Tiffany Tu, Daniel Rios
  @description: The function takes user inputted numbers until told to stop,
  then outputs the count, total sum, and average of the numbers,
  and finally classifies the average as negative, low, or high
  @date created: 10/04/2023
  @version: 1.00
  '''
  total = 0
  count = 0

  while True:
    #While function continuously takes in values until told to stop
    #.lower converts all characters in input to lowercase, so if the user
    #entered StOP the function still runs
    enter_number = input('Enter a number or say stop ')
    if enter_number.lower() == 'stop':
      break
    #Converts enter_number to integer, adds it to total intially at 0,
    #and adds 1 to count for every number input.
    enter_number = int(enter_number)
    total = total + enter_number
    count = count + 1
  #Calculates the average by dividing total by count
  #and outputs 0 as average if no number was entered by user
  if count > 0:
    average = total / count
  else:
    average = 0
#Prints the count, total sum, and average of the numbers input
  print(f'The count is {count}')
  print(f'The total sum is {total}')
  print(f'The average is {average:.2f}')
#Classifies the average as negative, low (under 100) or high (100+)
  if average < 0:
    print('The average is negative')
  elif 0 < average < 100:
    print('The average is low')
  else:
    print('The average is high')
#Return calls the total and average and outputs them together
  return total, average
sum_average()
