# -*- coding: utf-8 -*-
"""Practice_problem_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Go0Ye04U34tTbiCmg91TpgYQGn7-A8mc
"""

def lemon_juice(juice=2, water=16, syrup=2.5, servings=6):
  '''
  @File name: Practice_problem_5
  @Group: Team 8
  @Description: A recipe for lemon juice based on 4 variables
  @Authors: Adil Shafqat, Tiffany Tu, Daniel Rios
  @Date created: 10/2/2023
  @Version: 1.0
  '''
  # The function receives four variables from the user for a lemonade recipe
  # The function then prints a recipe for lemonade

  print(f'Lemon juice (in cups): {juice}')
  print(f'Water (in cups): {water}')
  print(f'Syrup (in cups): {syrup}')
  print(f'Total servings: {servings}')
  # The function then asks how the user how many total servings they would like
  # Then it prints the updated recipe
  total_serving = float(input('How many servings would you like to make? '))
  new_serving = total_serving / servings
  print('\nLemonade ingredients - yields', total_serving, 'servings')
  print(juice * new_serving, 'cup(s) lemon juice')
  print(water * new_serving, 'cup(s) water')
  print(syrup * new_serving, 'cup(s) syrup')
lemon_juice(4, 32, 10, 24)